const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "94773913394";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "unavailable" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Thaviya",

  sessionName:process.env.SESSION_ID || "SUHAIL_15_38_10_20_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICA0MyxcbiAgICAgICAgNDEsXG4gICAgICAgIDE1MyxcbiAgICAgICAgODEsXG4gICAgICAgIDE4LFxuICAgICAgICA3MixcbiAgICAgICAgNixcbiAgICAgICAgNzMsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTgyLFxuICAgICAgICAxNCxcbiAgICAgICAgMjIyLFxuICAgICAgICAxNzIsXG4gICAgICAgIDksXG4gICAgICAgIDg0LFxuICAgICAgICAyMjksXG4gICAgICAgIDE0NSxcbiAgICAgICAgNzcsXG4gICAgICAgIDEzMixcbiAgICAgICAgNDgsXG4gICAgICAgIDcsXG4gICAgICAgIDI3LFxuICAgICAgICAxOTIsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTc4LFxuICAgICAgICA5NCxcbiAgICAgICAgNzUsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjYsXG4gICAgICAgIDc3LFxuICAgICAgICA4NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxODEsXG4gICAgICAgIDEwMSxcbiAgICAgICAgNTcsXG4gICAgICAgIDI2LFxuICAgICAgICAxOTksXG4gICAgICAgIDczLFxuICAgICAgICA3LFxuICAgICAgICAxODAsXG4gICAgICAgIDk0LFxuICAgICAgICA5NyxcbiAgICAgICAgNTUsXG4gICAgICAgIDIxOSxcbiAgICAgICAgNTYsXG4gICAgICAgIDc0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDEzMixcbiAgICAgICAgNjQsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNDIsXG4gICAgICAgIDE0MixcbiAgICAgICAgODMsXG4gICAgICAgIDMyLFxuICAgICAgICAxNSxcbiAgICAgICAgNjIsXG4gICAgICAgIDIzLFxuICAgICAgICAyMDQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTMzLFxuICAgICAgICAyNixcbiAgICAgICAgNzEsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTIwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3MixcbiAgICAgICAgMjUsXG4gICAgICAgIDYsXG4gICAgICAgIDEwNyxcbiAgICAgICAgODIsXG4gICAgICAgIDg4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDMwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDIyLFxuICAgICAgICA3MixcbiAgICAgICAgMjU0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIxLFxuICAgICAgICAyNDYsXG4gICAgICAgIDkxLFxuICAgICAgICA3MixcbiAgICAgICAgOTAsXG4gICAgICAgIDI3LFxuICAgICAgICA4MCxcbiAgICAgICAgNDUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjQ0LFxuICAgICAgICAxODEsXG4gICAgICAgIDQsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjA5LFxuICAgICAgICA5LFxuICAgICAgICAxMzAsXG4gICAgICAgIDE5MCxcbiAgICAgICAgODIsXG4gICAgICAgIDExNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNTUsXG4gICAgICAgIDYyLFxuICAgICAgICAzNSxcbiAgICAgICAgNDIsXG4gICAgICAgIDExOSxcbiAgICAgICAgODksXG4gICAgICAgIDgwLFxuICAgICAgICAxMTksXG4gICAgICAgIDE2NixcbiAgICAgICAgMTIyLFxuICAgICAgICAzOSxcbiAgICAgICAgMjIzLFxuICAgICAgICAxNDksXG4gICAgICAgIDEzOCxcbiAgICAgICAgNjgsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTgzLFxuICAgICAgICA5OSxcbiAgICAgICAgMzIsXG4gICAgICAgIDQsXG4gICAgICAgIDI0MSxcbiAgICAgICAgNzYsXG4gICAgICAgIDI4LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI1MixcbiAgICAgICAgODIsXG4gICAgICAgIDgwLFxuICAgICAgICAyMDgsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjcsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTAyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDQsXG4gICAgICAgIDAsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMSxcbiAgICAgICAgMTExLFxuICAgICAgICAyMzEsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTI2LFxuICAgICAgICAxNzIsXG4gICAgICAgIDI3LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDc1LFxuICAgICAgICAxOTUsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTk0LFxuICAgICAgICA2NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDEyLFxuICAgICAgICA0OCxcbiAgICAgICAgNzQsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTAwLFxuICAgICAgICA3OSxcbiAgICAgICAgMjYsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjA0LFxuICAgICAgICAyMDIsXG4gICAgICAgIDIzLFxuICAgICAgICA5NCxcbiAgICAgICAgNzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgODMsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjM4LFxuICAgICAgICAxNzksXG4gICAgICAgIDIyNixcbiAgICAgICAgMTI4LFxuICAgICAgICAxOTYsXG4gICAgICAgIDExMSxcbiAgICAgICAgMzUsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMzcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjQzLFxuICAgICAgICAyNDksXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTUsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjYsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjMyLFxuICAgICAgICA3MSxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMzMsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMTIsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTA0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDY0LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgNDEsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICA3N1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDEwM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTI0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDEwLFxuICAgICAgICAxMDYsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNjYsXG4gICAgICAgIDc5LFxuICAgICAgICAxMTksXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTI4LFxuICAgICAgICAwLFxuICAgICAgICAxMzIsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMzgsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMCxcbiAgICAgICAgOTEsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNzUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgOTIsXG4gICAgICAgIDg3LFxuICAgICAgICAxMDAsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTc0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTY3LFxuICAgICAgICAxODEsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjAzLFxuICAgICAgICAyMTMsXG4gICAgICAgIDczLFxuICAgICAgICA1NCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxMDcsXG4gICAgICAgIDAsXG4gICAgICAgIDEwMixcbiAgICAgICAgMCxcbiAgICAgICAgMTEzLFxuICAgICAgICAxOTUsXG4gICAgICAgIDgzLFxuICAgICAgICAyMjIsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTM3LFxuICAgICAgICAzLFxuICAgICAgICA4NSxcbiAgICAgICAgMTI4LFxuICAgICAgICA2MSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxMTgsXG4gICAgICAgIDk1LFxuICAgICAgICAxOTIsXG4gICAgICAgIDc1LFxuICAgICAgICAxMTYsXG4gICAgICAgIDExLFxuICAgICAgICAxODMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTEwLFxuICBcImFkdlNlY3JldEtleVwiOiBcIlFRWW1wc2k1SFRGY2oyQnJzbk1tQ2lTOVluS092ZFM3WERBMFlKR1d2STA9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcInV4ellHLUo1U0kyWWVjSjBSTkJmRndcIixcbiAgXCJwaG9uZUlkXCI6IFwiNGVhNGQ0ODctNTBhNi00MjRhLTg5MDEtNWRkOTk3ZDFjNDcwXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEwNCxcbiAgICAgIDE3NSxcbiAgICAgIDEzOSxcbiAgICAgIDM3LFxuICAgICAgMTE5LFxuICAgICAgMTM0LFxuICAgICAgNTMsXG4gICAgICA4NixcbiAgICAgIDI1MixcbiAgICAgIDE1MSxcbiAgICAgIDEwLFxuICAgICAgNTUsXG4gICAgICAxNTAsXG4gICAgICAyMzcsXG4gICAgICAyNDMsXG4gICAgICAxMSxcbiAgICAgIDI3LFxuICAgICAgMjgsXG4gICAgICA4MSxcbiAgICAgIDE1NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNDcsXG4gICAgICAyMjIsXG4gICAgICAzNyxcbiAgICAgIDEyMSxcbiAgICAgIDE1MyxcbiAgICAgIDEyLFxuICAgICAgMTg3LFxuICAgICAgMjA5LFxuICAgICAgMTE2LFxuICAgICAgMjM2LFxuICAgICAgMTk1LFxuICAgICAgNTIsXG4gICAgICA4MixcbiAgICAgIDQxLFxuICAgICAgMTgwLFxuICAgICAgMTcsXG4gICAgICAxNTAsXG4gICAgICAzMSxcbiAgICAgIDIxMixcbiAgICAgIDE1MFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJDNjRKNDlIM1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTQ3NzM5MTMzOTQ6ODBAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjU4NzI5NDQ5OTc1ODkyOjgwQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ05xVzZkd05FSURJMUxnR0dCWWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiOWlvU1BrLzV1RUlFalBkZzJZMlhjSEFyUTJJNzlISm10QTRILy9hVk54TT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCIwRHFFZnZFZjJTU1FsUEdJS3BnVnZlbXVOS2dHT3BRWXBZNjdKb0xoK0NEUTBqSVpRYy9jd1VrV09ISGpNWFFqc2ZITmw5RUVnVGhsenZqWFdxWUNBQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJXQlFVZnNZYmlOOWtMdXZCZGJZeWpYNkxvZk9EaFB4L2tHRFNuNkZzbWZZZTlRS1VRa2h5aUsrVUovSlBFNDc3c3V3YlpYQnhndGRHejJtenFhdzdBQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5NDc3MzkxMzM5NDo4MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICA0MixcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA2MixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDE5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJpcGhvbmVcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyOTQzODcyMSxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQVBHL1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEcvLmpzb24iOiB7fQp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
